#!/usr/bin/env bash
# PreToolUse (Edit|Write): refuse direct edits to generated or vendored files.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
read_hook_input
file="$(rel_path "$(jfield tool_input.file_path)")"
[[ -z "$file" ]] && exit 0

deny() { echo "Blocked edit to $file: $1" >&2; exit 2; }
case "$file" in
  sim/app.bundle.js) deny "it is the esbuild output. Edit sim/src/** and run 'cd sim && npm run build'." ;;
  sim/package-lock.json) deny "lockfiles change only through npm (npm install <pkg>)." ;;
  flake.lock) deny "use 'nix flake update [input]' instead." ;;
  tex/acmart.cls|tex/ACM-Reference-Format.bst) deny "vendored ACM class/style; never modify." ;;
  *.dout) deny "it is generated by determinize_main. Change the .det source or the OCaml code, then run ./det.sh (or ./run.sh FILE)." ;;
  *.tra|*.lab|*.state.rew) deny "Storm files are generated by './run.sh --storm FILE'." ;;
  tex/*.aux|tex/*.bbl|tex/*.log|tex/*.fls|tex/*.fdb_latexmk|tex/*.out|tex/*.blg) deny "LaTeX build artifact." ;;
  .direnv/*|*/_build/*|*/node_modules/*) deny "build cache." ;;
esac
exit 0
