import Determinize.Proof.TraceSoundness
import Determinize.Spec.Traces.Main

/-!
# Compact traces

The compact trace of a detailed step trace retains its general-affinity draws (`retain`), and the
measurable structure of compact traces is generated by their length and coordinates.
-/

namespace Determinize.Proof.StepTraces
open MeasureTheory ProbabilityTheory Determinize.Spec.Paper Determinize.Proof.StepTraces
open Determinize.Proof.Paper
open scoped ProbabilityTheory
noncomputable section
open Classical

abbrev DrawTrace := Determinize.Spec.Traces.Trace

theorem draw_length_measurable : Measurable (List.length : DrawTrace → Nat) :=
  measurable_fst.comp (comap_measurable _)

theorem draw_event_measurable (i : Nat) :
    Measurable (fun trace : DrawTrace => trace.getD i (.uniform, 0)) := by
  have h : Measurable (fun trace : DrawTrace =>
      (trace.length, fun j : Nat => trace.getD j (.uniform, 0))) := comap_measurable _
  exact (measurable_pi_apply i).comp (measurable_snd.comp h)

theorem draw_cons_measurable :
    Measurable (fun p : (Op × ℝ) × DrawTrace => p.1 :: p.2) := by
  apply measurable_comap_iff.mpr
  refine Measurable.prodMk ((draw_length_measurable.comp measurable_snd).add_const 1) ?_
  apply measurable_pi_lambda
  intro i
  cases i with
  | zero => exact measurable_fst
  | succ i => exact (draw_event_measurable i).comp measurable_snd

theorem draw_tail_measurable : Measurable (List.tail : DrawTrace → DrawTrace) := by
  apply measurable_comap_iff.mpr
  refine Measurable.prodMk ?_ ?_
  · simpa using draw_length_measurable.sub_const 1
  · apply measurable_pi_lambda
    intro i
    simpa using draw_event_measurable (i+1)

def emitDraw (event : Event) (trace : DrawTrace) : DrawTrace :=
  match event with | none => trace | some draw => draw :: trace

theorem event_elim_measurable {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    (empty : α → β) (draw : (Op × ℝ) × α → β)
    (he : Measurable empty) (hd : Measurable draw) :
    Measurable (fun p : Event × α => p.1.elim (empty p.2) (fun d => draw (d,p.2))) := by
  let f : (Sum (Op × ℝ) PUnit) × α → β := fun p =>
    match p.1 with | .inl d => draw (d,p.2) | .inr _ => empty p.2
  have hf : Measurable f := by
    convert (hd.sumElim (he.comp measurable_snd)).comp
      (MeasurableEquiv.sumProdDistrib (Op × ℝ) PUnit α).measurable using 1
    funext ⟨e,a⟩
    cases e <;> rfl
  have h := hf.comp ((comap_measurable (Equiv.optionEquivSumPUnit.{0} (Op × ℝ))).prodMap (measurable_id (α := α)))
  convert h using 1
  funext ⟨e,a⟩
  cases e <;> rfl

theorem emitDraw_measurable : Measurable (fun p : Event × DrawTrace => emitDraw p.1 p.2) := by
  convert event_elim_measurable id (fun p => p.1 :: p.2) measurable_id draw_cons_measurable using 1
  funext ⟨e,a⟩
  cases e <;> rfl

def retainWithin : Nat → Trace → DrawTrace
  | 0, _ => []
  | n+1, trace => emitDraw (trace.headD none) (retainWithin n trace.tail)

theorem retainWithin_measurable (n : Nat) : Measurable (retainWithin n) := by
  induction n with
  | zero => exact measurable_const
  | succ n ih =>
      exact emitDraw_measurable.comp
        (trace_head_measurable.prodMk (ih.comp trace_tail_measurable))

def retain (trace : Trace) : DrawTrace := trace.filterMap id

theorem retain_eq (trace : Trace) : retain trace = retainWithin trace.length trace := by
  induction trace with
  | nil => rfl
  | cons head tail ih => cases head <;> simp_all [retain, retainWithin, emitDraw]

theorem retain_measurable : Measurable retain := by
  rw [funext retain_eq]
  have h : Measurable (fun p : Nat × Trace => retainWithin p.1 p.2) :=
    measurable_from_prod_countable_right retainWithin_measurable
  exact h.comp (trace_length_measurable.prodMk measurable_id)

end
end Determinize.Proof.StepTraces
