name = "determinize"
version = "0.1.0"
defaultTargets = ["Determinize", "determinize", "det-tests"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.1"

[[lean_lib]]
name = "Determinize"

[[lean_exe]]
name = "determinize"
root = "Main"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "det-tests"
root = "Tests.Main"
