import Determinize.Spec.FiniteModel.Safety
import Determinize.Spec.Traces.Semantics
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.Logic.Equiv.Option
import Mathlib.Probability.Kernel.Composition.MeasureCompProd
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# Internal traces with one entry per reduction step

A trace records one entry per reduction step: a generation-affinity primitive and
its sampled value, or `none` for a step without a generation-affinity draw. Its
length is the first termination depth. Expectation-affinity sampled values are not recorded.
-/

namespace Determinize.Proof.StepTraces

open MeasureTheory ProbabilityTheory Determinize.Spec.Paper

abbrev Event := Option (Op × ℝ)

instance : MeasurableSpace Event :=
  MeasurableSpace.comap (Equiv.optionEquivSumPUnit.{0} (Op × ℝ)) inferInstance

abbrev Trace := List Event
abbrev Output := Trace × ℝ

/-- Measurability is generated by trace length and individual events. -/
instance : MeasurableSpace Trace :=
  MeasurableSpace.comap (fun trace : Trace =>
    (trace.length, fun index : Nat => trace.getD index none)) inferInstance

def generationEvent : DistributionAction × Op → ℝ → Event
  | (.sample .G, op), value => some (op, value)
  | _, _ => none

def prepend (entry : Event) (output : Output) : Output :=
  (entry :: output.1, output.2)

/-- Joint trace/output law of executions first returning a real at exactly `depth`. -/
noncomputable def exactMeasure : Nat → Expr → Measure Output
  | 0, .real value => Measure.dirac ([], value)
  | 0, _ => 0
  | depth + 1, expression =>
      if expression.isValue then 0
      else match reduce expression with
        | .next next => (exactMeasure depth next).map (prepend none)
        | .sample modeTag fiber continuation => fiber.bind fun value =>
            (exactMeasure depth (continuation value)).map (prepend (generationEvent modeTag value))
        | .stuck => 0

/-- Joint operational law of terminating traces and returned expectation-affinity reals. -/
noncomputable def jointMeasure (program : Expr) : Measure (Trace × ℝ) :=
  Measure.sum fun depth => exactMeasure depth program

/-- Erasing terminating traces recovers the ordinary output semantics. -/
def correspondenceThm : Prop :=
  ∀ program : Expr, (jointMeasure program).map Prod.snd = bigStepMeasure program

end Determinize.Proof.StepTraces
