import Determinize.Traces.Semantics
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.Logic.Equiv.Option
import Mathlib.Probability.Kernel.Composition.MeasureCompProd
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# Internal traces with one entry per reduction step

A trace records one entry per reduction step: a generation-mode primitive and
its sampled value, or `none` for a step without a generation-mode draw. Its
length is the first termination depth. Expectation-mode sampled values are not recorded.
-/

namespace Determinize.Proof.StepTraces

open MeasureTheory ProbabilityTheory Determinize.Statement.Paper

abbrev Event := Option (Op × ℝ)

instance : MeasurableSpace Event :=
  MeasurableSpace.comap (Equiv.optionEquivSumPUnit.{0} (Op × ℝ)) inferInstance

abbrev Trace := List Event
abbrev Output := Trace × ℝ

/-- Measurability is generated by trace length and individual events. -/
instance : MeasurableSpace Trace :=
  MeasurableSpace.comap (fun trace : Trace =>
    (trace.length, fun index : Nat => trace.getD index none)) inferInstance

def generationEvent : Mode × Kind × Op → ℝ → Event
  | (.G, .stochastic, op), value => some (op, value)
  | _, _ => none

def prepend (entry : Event) (output : Output) : Output :=
  (entry :: output.1, output.2)

/-- Joint trace/output law of executions first returning a real at exactly `depth`. -/
noncomputable def exactMeasure : Nat → Expr → Measure Output
  | 0, .real value => Measure.dirac ([], value)
  | 0, _ => 0
  | depth + 1, expression =>
      if expression.isValue then 0
      else match reduce expression with
        | .next next => (exactMeasure depth next).map (prepend none)
        | .sample modeTag fiber continuation => fiber.bind fun value =>
            (exactMeasure depth (continuation value)).map (prepend (generationEvent modeTag value))
        | .stuck => 0

/-- Joint operational law of terminating traces and returned expectation-mode reals. -/
noncomputable def jointMeasure (program : Expr) : Measure (Trace × ℝ) :=
  Measure.sum fun depth => exactMeasure depth program

/-- Erasing terminating traces recovers the ordinary output semantics. -/
def correspondenceThm : Prop :=
  ∀ program : Expr, (jointMeasure program).map Prod.snd = bigStepMeasure program

/-- The actual source and target joint laws factor over the same operational traces. -/
def MeanOnTraces (source target : Expr) : Prop :=
  ∃ (traces : Measure Trace) (fiber : Kernel Trace ℝ) (output : Trace → ℝ),
    traces Set.univ ≤ 1 ∧
    IsMarkovKernel fiber ∧
    Measurable output ∧
    jointMeasure source = traces ⊗ₘ fiber ∧
    jointMeasure target = traces.map (fun trace => (trace, output trace)) ∧
    ∀ᵐ trace ∂traces,
      Integrable id (fiber trace) ∧ output trace = ∫ value : ℝ, value ∂fiber trace

/-- Trace soundness for expectation-mode programs on detailed traces, without a global
integrability assumption. General-mode programs are handled by the compact layer, which
promotes them. -/
def soundnessThm : Prop :=
  ∀ program : Expr,
    Typed [] program (.float .E) → program.sourceForm = true → DoesNotGetStuck program →
      DoesNotGetStuck program.determinize ∧ MeanOnTraces program program.determinize


end Determinize.Proof.StepTraces
