#!/usr/bin/env python3
"""Generate exact moments and variance reduction factors for the introduction.

Run from any directory with Python 3. Output is committed beside the figures.
These calculations use real-distribution moments, not floating-point estimates.
"""

from fractions import Fraction as F
from math import factorial
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'tex/figures/data'


def moments():
    # X ~ U(0,1), Z ~ N(0,1) independently: XY = X² + XZ, target = X².
    signal_mean = F(1, 3)
    signal_target = F(1, 5) - signal_mean**2
    signal_source = signal_target + F(1, 3)

    # N counts non-exit rooms: P(N=n)=(1/4)(3/4)^n, starting at depth 1.
    # E[(N)_k] = k! (q/p)^k for falling factorials (N)_k.
    p = F(1, 4)
    q = 1 - p
    falling = [factorial(k) * (q / p)**k for k in range(5)]
    n1 = falling[1]
    n2 = falling[2] + falling[1]
    n3 = falling[3] + 3 * falling[2] + falling[1]
    n4 = falling[4] + 6 * falling[3] + 7 * falling[2] + falling[1]
    # Conditional mean = sum(2d, d=1..N) = N(N+1).
    dungeon_mean = n2 + n1
    dungeon_target = n4 + 2 * n3 + n2 - dungeon_mean**2
    # A room pays 200d with probability 1/100: variance = 396d².
    sum_squares = (2 * n3 + 3 * n2 + n1) / 6
    jackpot = F(1, 100)
    removed_variance = 200**2 * jackpot * (1 - jackpot) * sum_squares
    dungeon_source = dungeon_target + removed_variance
    return {
        'signal': (signal_mean, signal_source, signal_target),
        'dungeon': (dungeon_mean, dungeon_source, dungeon_target),
    }


def tex_fraction(value):
    if value.denominator == 1:
        return str(value.numerator)
    return rf'\frac{{{value.numerator}}}{{{value.denominator}}}'


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    definitions = ['% Generated by tools/paper-plots.py.']
    for name, (mean, source, target) in moments().items():
        values = {'Mean': mean, 'SourceVariance': source, 'TargetVariance': target}
        for suffix, value in values.items():
            definitions.append(rf'\newcommand{{\{name}{suffix}}}{{{tex_fraction(value)}}}')
            definitions.append(rf'\newcommand{{\{name}{suffix}Value}}{{{float(value):.17g}}}')
        definitions.append(rf'\newcommand{{\{name}Reduction}}{{{float(source / target):.2f}}}')
        print(f'{name}: mean={mean}, variance {source} -> {target}')
    (OUTPUT / 'intro-statistics.tex').write_text('\n'.join(definitions) + '\n')


if __name__ == '__main__':
    main()
